// Array de mensagens carinhosas
const mensagens = [
    "Você é a luz dos meus dias.",
    "Tenha um dia maravilhoso, meu amor.",
    "Sua presença torna tudo melhor.",
    "No calor dos teus abraços, encontro meu refúgio e minha paz. Obrigado por me acolher sempre, meu amor. Estarei sempre aqui, fazendo o mesmo por você.",
    "Você é a luz da minha vida. Cada dia ao seu lado é um presente que a vida me deu, e eu sou eternamente grato por ter você como minha namorada.",
    "Você é a luz que ilumina o meu caminho e o motivo do meu sorriso todos os dias. Te amo mais do que você pode imaginar.",
    "Minha amada, agradeço todos os dias por ter você ao meu lado. Meu amor por você sempre será forte e puro. Te amo de todo o meu coração!",
    "Seu sorriso é um raio de Sol que ilumina meu dia, e seu abraço, o lugar mais acolhedor do mundo. Você é minha felicidade, meu amor.",
    "Em cada batida do meu coração, ecoa o amor que sinto por você. Você é a minha luz, meu sorriso, minha vida. Te amo, ontem, hoje, amanhã e para sempre.",
    "O mundo é melhor com você nele!",
    "Cada dia ao seu lado é um presente.",
    "Seu sorriso é a luz dos meus dias.",
    "Amo a forma como você faz tudo parecer fácil.",
    "Você é a razão do meu sorriso diário.",
    "Sinto-me sortudo por ter você na minha vida.",
    "Minha vida é mais colorida com você.",
    "Você torna todos os dias especiais.",
    "Cada momento contigo é precioso para mim.",
    "Amo a forma como seu toque acalma meu coração.",
    "Você é a estrela que ilumina minha escuridão.",
    "Com você, cada dia é Dia dos Namorados.",
    "Agradeço por cada risada que compartilhamos.",
    "Você é meu porto seguro em tempestades.",
    "Seu abraço é meu lugar favorito na Terra.",
    "Sinto-me completo(a) ao seu lado.",
    "Seu amor é a melhor parte do meu dia.",
    "Você é a melodia da minha canção.",
    "Amo a forma como você enxerga o mundo.",
    "Você transforma meus dias com sua presença.",
    "Minha felicidade tem o seu nome.",
    "Amar você é a coisa mais fácil do mundo.",
    "Com você, cada momento é mágico.",
    "Você é a inspiração por trás dos meus sonhos.",
    "A distância só aumenta meu amor por você.",
    "Cada detalhe seu é motivo para sorrir.",
    "Você é o meu conto de fadas real.",
    "Meu coração bate mais forte por você.",
    "Você é o sol que ilumina meus dias nublados.",
    "Nossas memórias são meu tesouro mais precioso.",
    "Agradeço por cada risada que compartilhamos.",
    "Você é a razão pela qual a vida é tão doce.",
    "Seu amor é meu maior presente.",
    "Você é o que eu sempre quis e mais um pouco.",
    "O amor que sinto por você é eterno.",
    "Você é o meu farol em noites escuras.",
    "A cada batida do meu coração, sinto seu amor.",
    "Seu abraço é o melhor lugar do mundo.",
    "Amo a forma como você cuida de mim.",
    "Com você, cada dia é uma aventura.",
    "Você é minha melhor metade.",
    "Agradeço por cada momento ao seu lado.",
    "Você é minha sorte em forma de pessoa.",
    "Seu sorriso é meu raio de sol.",
    "Você é a razão do meu brilho nos olhos.",
    "Minha vida é mais bonita com você.",
    "Com você, o amor é sempre jovem.",
    "Seu amor é meu maior conforto.",
    "Você é minha fonte constante de felicidade.",
    "Cada dia é uma nova chance de amar você.",
    "Você é meu maior presente de Deus.",
    "Sua voz é a melodia da minha vida.",
    "A cada dia, descubro novas razões para amar você.",
    "Você é meu anjo na Terra.",
    "Com você, o amor é a única resposta.",
    "Nossas risadas são a trilha sonora do meu coração.",
    "Você é a página mais bonita do meu livro.",
    "Seu amor é a tinta que colore minha vida.",
    "Cada momento contigo é um sonho realizado.",
    "A distância é apenas um detalhe para nós.",
    "Você é a essência da minha felicidade.",
    "Meu coração só pertence a você.",
    "Amo a forma como você torna tudo especial.",
    "Seu amor é a força que me impulsiona.",
    "Você é minha bússola na jornada da vida.",
    "Seu abraço é meu refúgio seguro.",
    "A cada batida do meu coração, seu nome ecoa.",
    "Com você, até os dias comuns são extraordinários.",
    "Você é o sonho que nunca quero acordar.",
    "Meu amor por você é infinito.",
    "Você é a luz que ilumina meu caminho.",
    "Cada palavra sua é uma melodia para os meus ouvidos.",
    "Você é meu presente mais precioso.",
    "Seu amor é o combustível da minha felicidade.",
    "Você é minha fortaleza nas horas difíceis.",
    "Com você, cada momento é uma joia rara.",
    "Amo a forma como você ilumina minha vida.",
    "Você é o motivo do meu sorriso bobo.",
    "Minha gratidão por ter você é imensurável.",
    "Seu amor é meu abrigo seguro.",
    "Com você, o amor é a resposta para tudo.",
    "Você é o arco-íris após a tempestade da vida.",
    "Amo a forma como você faz meu coração dançar.",
    "Seu amor é o maior presente da minha vida.",
    "Você é a razão pela qual a vida é tão bela.",
    "Cada dia ao seu lado é uma benção.",
    "Com você, o amor é uma jornada eterna.",
    "Você é o tesouro no fim do arco-íris da minha vida.",
    "Seu amor é a luz que guia meus dias.",
    "Você é minha inspiração constante.",
    "Amo a forma como você preenche meu coração.",
    "Você é a razão pela qual a vida é extraordinária.",
    "Com você, o amor é a resposta para cada pergunta.",
    "Você é o sol que aquece minha alma.",
    "Seu amor é a chama que nunca se apaga.",
    "Você é minha razão para acreditar em amor eterno.",
    "Amo a forma como você torna cada momento mágico.",
    "Cada dia é uma nova chance de amar você ainda mais.",
    "Você é a estrela que ilumina a escuridão da minha vida.",
    "Com você, o amor é a melodia que nunca para de tocar.",
    "Você é a poesia que embala meu coração.",
    "Seu amor é a força que me sustenta.",
    "Amo a forma como você colore minha vida.",
    "Você é minha bênção diária.",
    "Com você, cada dia é um presente divino.",
    "Você é meu lar em forma de pessoa.",
    "Com você, a vida é uma constante primavera.",
    "Seu amor é o segredo da minha felicidade.",
    "Você é a música que embala meu coração.",
    "Com você, até os dias chuvosos são ensolarados.",
    "Amo a forma como você ilumina meu mundo.",
    "Você é o sonho que nunca quero esquecer.",
    "Meu coração bate no ritmo do seu amor.",
    "Você é a estrela brilhante no meu céu.",
    "Com você, cada dia é uma página de amor.",
    "Seu sorriso é o raio de sol nos meus dias nublados.",
    "Você é a inspiração por trás dos meus suspiros.",
    "Amo a forma como você torna simples momentos especiais.",
    "Com você, cada abraço é uma cura para a alma.",
    "Você é a luz no fim do túnel da minha vida.",
    "Seu amor é a doce melodia da minha existência.",
    "Você é meu conto de fadas da vida real.",
    "Com você, cada beijo é um capítulo de romance.",
    "Você é a razão pela qual a vida é uma aventura.",
    "Seu abraço é o abrigo perfeito nos dias frios.",
    "Você é o arco-íris após a tempestade da vida.",
    "Com você, cada olhar é uma troca de juras de amor.",
    "Amo a forma como você faz meu coração dançar.",
    "Você é a inspiração para minhas mais belas poesias.",
    "Seu amor é a chama que aquece meu coração.",
    "Você é o tesouro no fundo do oceano do meu amor.",
    "Com você, cada suspiro é uma declaração de amor.",
    "Você é a estrela-guia na jornada da minha vida.",
    "Seu amor é a mágica que transforma meus dias.",
    "Você é o oceano de ternura nos meus pensamentos.",
    "Com você, cada momento é uma eternidade de amor.",
    "Amo a forma como você preenche meu mundo de cor.",
    "Você é a razão pela qual a vida é um presente.",
    "Seu abraço é o refúgio nos dias turbulentos.",
    "Você é a fonte da alegria no meu coração.",
    "Com você, cada palavra é uma promessa de amor.",
    "Amo a forma como você faz meu coração sorrir.",
    "Você é o farol que guia meu barco na escuridão.",
    "Seu amor é a canção que embala meu sono.",
    "Você é a inspiração para todos os meus sonhos.",
    "Com você, cada toque é uma carícia na alma.",
    "Você é o motivo pelo qual a vida é uma festa.",
    "Seu sorriso é a luz que clareia meu caminho.",
    "Você é a razão pela qual meu coração bate forte.",
    "Com você, cada amanhecer é um novo começo de amor.",
    "Amo a forma como você enfeita meus dias.",
    "Você é a magia que transforma o ordinário em extraordinário.",
    "Seu amor é a cola que une os pedaços do meu coração.",
    "Você é a razão pela qual a vida é um poema.",
    "Com você, cada pôr do sol é um espetáculo de amor.",
    "Amo a forma como você é a peça que faltava no meu quebra-cabeça.",
    "Você é a inspiração para todos os meus sorrisos.",
    "Seu amor é a brisa que acaricia meu coração.",
    "Você é o diamante raro no meu cofre de afeto.",
    "Com você, cada segundo é um tesouro inestimável.",
    "Amo a forma como você é a estrela guia na minha noite escura.",
    "Você é a razão pela qual a vida é um jardim de amor.",
    "Seu sorriso é o farol que ilumina meu caminho.",
    "Com você, cada dia é uma tela em branco de amor.",
    "Você é a inspiração por trás dos meus mais belos sonhos.",
    "Seu amor é a melodia que embala minha alma.",
    "Você é o poema que escrevo todos os dias.",
    "Amo a forma como você é a resposta para todas as minhas preces.",
    "Você é a razão pela qual a vida é uma canção de amor.",
    "Seu abraço é o abrigo seguro nos momentos de tempestade.",
    "Você é o sol que ilumina até os dias mais chuvosos.",
    "Com você, cada noite é uma sinfonia de amor.",
    "Amo a forma como você é a razão pela qual a vida é bela.",
    "Você é a inspiração para todas as minhas boas ações.",
    "Seu amor é o tesouro escondido no meu coração.",
    "Você é a razão pela qual meu coração bate no ritmo do amor.",
    "Com você, cada passo é uma dança de alegria.",
    "Amo a forma como você é a poesia que escrevo todos os dias.",
    "Você é a razão pela qual a vida é uma jornada incrível.",
    "Seu sorriso é a luz que guia meu caminho.",
    "Com você, cada amanhã é uma promessa de amor eterno.",
    "Você é a inspiração por trás dos meus momentos mais felizes.",
    "Seu amor é a chama que nunca se apaga em meu coração.",
    "Você é o presente mais precioso no meu pacote da felicidade.",
    "Amo a forma como você é a razão pela qual a vida é doce.",
    "Você é a estrela que ilumina o palco da minha vida.",
    "Com você, cada suspiro é uma declaração de eterno amor.",
    "Seu abraço é o abrigo seguro nos dias mais frios.",
    "Você é a fonte da alegria nos meus dias.",
    "Amo a forma como você é a nota mais alta na sinfonia da minha vida.",
    "Você é a razão pela qual a vida é um conto de fadas.",
    "Seu sorriso é a luz que ilumina meu mundo escuro.",
    "Com você, cada dia é uma obra-prima de amor.",
    "Você é a inspiração para todos os meus melhores momentos.",
    "Seu amor é a cola que mantém unidos os pedaços do meu coração.",
    "Você é a razão pela qual meu coração bate no compasso do amor.",
    "Com você, cada passo é uma dança de alegria e gratidão.",
    "Amo a forma como você é a melodia que embala meus sonhos.",
    "Você é a estrela que brilha mais forte no meu céu.",
    "Seu sorriso é a luz que clareia meus dias mais sombrios.",
    "Você é a razão pela qual a vida é uma jornada extraordinária.",
    "Com você, cada noite é uma celebração de amor e paz.",
    // Adicione mais mensagens conforme necessário
];

// Exiba uma mensagem aleatória
const mensagemElemento = document.getElementById("mensagem");
const mensagemAleatoria = mensagens[Math.floor(Math.random() * mensagens.length)];
mensagemElemento.textContent = mensagemAleatoria;

function criarChuvaDeCoracoes() {
    const numeroDeCoracoes = 30;

    for (let i = 0; i < numeroDeCoracoes; i++) {
        criarCoração();
    }
}

function criarCoração() {
    const coracao = document.createElement("div");
    coracao.className = "heart";
    coracao.innerHTML = "&#10084;"; // Código de caractere para um coração

    const posX = Math.random() * window.innerWidth;
    const duracao = Math.random() * 2 + 1; // Duração da animação entre 1 e 3 segundos

    coracao.style.left = `${posX}px`;
    coracao.style.animationDuration = `${duracao}s`;

    document.body.appendChild(coracao);

    coracao.addEventListener("animationend", () => {
        coracao.remove(); // Remova o coração quando a animação terminar
    });
}

